const questions = {
  // response_code: 0,
  results: [
    {
      category: 'Science: Gadgets',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What are the base station trackers used for the HTC Vive called?',
      correct_answer: 'Lighthouse',
      incorrect_answers: ['Motion', 'Constellation ', 'Trackers'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'boolean',
      difficulty: 'medium',
      question: 'Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.',
      correct_answer: 'True',
      incorrect_answers: ['False'],
    },
    {
      category: 'Entertainment: Music',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What is the stage name of English female rapper Mathangi Arulpragasam, who is known for the song &quot;Paper Planes&quot;?',
      correct_answer: 'M.I.A.',
      incorrect_answers: ['K.I.A.', 'C.I.A.', 'A.I.A.'],
    },
    {
      category: 'Entertainment: Japanese Anime & Manga',
      type: 'multiple',
      difficulty: 'hard',
      question: 'In &quot;One Piece&quot;, who confirms the existence of the legendary treasure, One Piece?',
      correct_answer: 'Edward &quot;Whitebeard&quot; Newgate',
      incorrect_answers: [
        'Former Marine Fleet Admiral Sengoku',
        'Pirate King Gol D Roger',
        'Silvers Rayleigh',
      ],
    },
    {
      category: 'Science & Nature',
      type: 'multiple',
      difficulty: 'medium',
      question: 'In human biology, a circadium rhythm relates to a period of roughly how many hours?',
      correct_answer: '24',
      incorrect_answers: ['8', '16', '32'],
    },
    {
      category: 'Science: Gadgets',
      type: 'multiple',
      difficulty: 'medium',
      question: 'What are the base station trackers used for the HTC Vive called?',
      correct_answer: 'Lighthouse',
      incorrect_answers: ['Motion', 'Constellation ', 'Trackers'],
    },
    {
      category: 'Entertainment: Video Games',
      type: 'boolean',
      difficulty: 'medium',
      question: 'Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.',
      correct_answer: 'True',
      incorrect_answers: ['False'],
    },
    {
      category: 'Entertainment: Music',
      type: 'multiple',
      difficulty: 'easy',
      question: 'What is the stage name of English female rapper Mathangi Arulpragasam, who is known for the song &quot;Paper Planes&quot;?',
      correct_answer: 'M.I.A.',
      incorrect_answers: ['K.I.A.', 'C.I.A.', 'A.I.A.'],
    },
    {
      category: 'Entertainment: Japanese Anime & Manga',
      type: 'multiple',
      difficulty: 'hard',
      question: 'In &quot;One Piece&quot;, who confirms the existence of the legendary treasure, One Piece?',
      correct_answer: 'Edward &quot;Whitebeard&quot; Newgate',
      incorrect_answers: [
        'Former Marine Fleet Admiral Sengoku',
        'Pirate King Gol D Roger',
        'Silvers Rayleigh',
      ],
    },
    {
      category: 'Science & Nature',
      type: 'multiple',
      difficulty: 'medium',
      question: 'In human biology, a circadium rhythm relates to a period of roughly how many hours?',
      correct_answer: '24',
      incorrect_answers: ['8', '16', '32'],
    },
  ],
};

export default questions;
